# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-30 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, verbose_name='用戶姓名')),
                ('password', models.CharField(max_length=32, verbose_name='用戶密碼')),
                ('email', models.EmailField(max_length=32, verbose_name='email')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
