# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-30 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_brand', models.CharField(max_length=50, verbose_name='商品品牌')),
                ('com_sort', models.CharField(max_length=50, verbose_name='商品分類')),
                ('com_keyword', models.CharField(max_length=50, verbose_name='商品關鍵字')),
                ('com_name', models.CharField(max_length=300, verbose_name='商品名稱')),
                ('com_price', models.CharField(default=0, max_length=32, verbose_name='商品價格範圍')),
                ('com_number', models.CharField(max_length=50, verbose_name='商品編號')),
                ('com_exist', models.CharField(max_length=1, verbose_name='商品是否存在')),
                ('com_picture', models.CharField(max_length=300, verbose_name='商品圖片')),
                ('com_follower', models.ManyToManyField(to='user.UserProfile')),
            ],
            options={
                'db_table': 'commodity',
            },
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=100, verbose_name='商品姓名')),
                ('com_price', models.IntegerField(verbose_name='商品價格')),
                ('mall_name', models.CharField(max_length=100, verbose_name='商城名稱')),
                ('com_web_url', models.CharField(max_length=300, verbose_name='商城網址')),
                ('mall_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Commodity')),
            ],
            options={
                'db_table': 'mall',
            },
        ),
    ]
